name: Check Markdown Links

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          # Check all markdown files
          args: --verbose --no-progress './**/*.md'
          fail: false
          
      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 🔗 Broken Links Found
          content-filepath: ./lychee/out.md
          labels: |
            broken-links
            automated-issue